version: '3.1'

services:

  rabbitmq:
    image: rabbitmq:3.7.7-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - 5672:5672
      - 15672:15672

  postgres:
    image: postgres:10.4-alpine
    environment:
      - POSTGRES_DB=notification-service
      - POSTGRES_USER=ibank
      - POSTGRES_PASSWORD=knabi
    ports:
      - 5432:5432
